# Generated by Django 2.2 on 2019-11-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogposts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(default='Hello World'),
            preserve_default=False,
        ),
    ]
